# Generated by Django 2.1 on 2018-08-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default='location default text', max_length=120, null=True),
        ),
    ]
